# Generated by Django 5.0.1 on 2024-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="İHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("weight", models.FloatField()),
                ("category", models.CharField(max_length=50)),
                ("image", models.CharField(blank=True, max_length=30, null=True)),
                ("builtIn", models.BooleanField(default=True)),
            ],
        ),
    ]
