# Generated by Django 5.0.1 on 2024-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("İha", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="i̇ha",
            name="builtIn",
        ),
        migrations.AddField(
            model_name="i̇ha",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="i̇ha",
            name="image",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
